# Training configuration
GPU: [0,1,2,3]

VERBOSE: False

GCNET:
  IMG_SIZE: 256
  PATCH_SIZE: 4
  EMB_DIM: 96
  DEPTH_EN: [8, 8, 8, 8]
  PATCH_NORM: True
  USE_CHECKPOINTS: False
  FINAL_UPSAMPLE: 'Dual up-sample'

  # GC Hyperparameters
  CONTEXT_RATIO: 0.125
  POOLING_TYPE: 'avg'
  FUSION_TYPES: ['channel_add']

MODEL:
  MODE: 'Denoising'

# Optimization arguments.
OPTIM:
  BATCH: 8
  EPOCHS: 100
  # EPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: 'datasets/train'       # path to training data
  VAL_DIR: 'datasets/test' # path to validation data
  SAVE_DIR: 'checkpoints'           # path to save models and images
